# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    nelmio_cors:
        defaults:
            origin_regex: true
            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
            allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            expose_headers: [ 'Link' ]
            max_age: 3600
        paths:
            '^/api/':
                allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
                allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
                allow_headers: [ 'Content-Type', 'Authorization' ]
                expose_headers: [ 'Link' ]
                max_age: 3600
    serializer: { enable_annotations: true }
    default_locale: fr
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
