monolog:
  channels: ["deprecation"]
  handlers:
    main:
      type: stream
      path: "%kernel.project_dir%/var/log/%kernel.environment%.log"
      level: debug
      channels: ["!event"]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]

    # Log deprecations
    deprecation:
      type: stream
      path: "%kernel.project_dir%/var/log/%kernel.environment%.deprecations.log"
      level: info
      channels: ["deprecation"]

    # Uncomment the following lines for browser logging
    # You may have to allow bigger header sizes in your Web server configuration
    # firephp:
    #     type: firephp
    #     level: info
    # chromephp:
    #     type: chromephp
    #     level: info

services:
  monolog.processor.psr_log_message:
    class: Monolog\Processor\PsrLogMessageProcessor
    tags: [monolog.processor]
