controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

api_login_check:
  path: /api/login_check

app_register:
  path: /api/register
  controller: App\Controller\RegistrationController::register
  methods: POST

user_data:
  path: /api/user_data
  controller: App\Controller\UserController::getUserData
