controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

api_login_check:
  path: /api/login_check

app_register:
  path: /api/register
  controller: App\Controller\RegistrationController::register
  methods: POST

user_data:
  path: /api/user_data
  controller: App\Controller\UserController::getUserData

user_update:
  path: /api/user_update
  controller: App\Controller\UserController::update
  methods: PATCH

organization_new:
  path: /api/organization_new
  controller: App\Controller\OrganizationController::create
  methods: POST

organization_update:
  path: /api/organization_update/{id}
  controller: App\Controller\OrganizationController::update
  methods: PATCH

preferencies_update:
  path: /api/preferencies_update
  controller: App\Controller\PreferenciesController::update
  methods: PATCH

upload_image:
    path: /uploads/images/
    controller: App\Controller\UploadController::uploadImage
    methods: POST

delete_image:
    path: /uploads/images/
    controller: App\Controller\UploadController::deleteImage
    methods: DELETE


rent_new:
  path: /api/rent_request
  controller: App\Controller\RentController::create
  methods: POST

update_rent:
  path: /api/rent_update/{id}
  controller: App\Controller\RentController::update
  methods: PATCH