controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

api_login_check:
  path: /api/login_check

app_register:
  path: /api/register
  controller: App\Controller\RegistrationController::register
  methods: POST

user_data:
  path: /api/user_data
  controller: App\Controller\UserController::getUserData

user_update:
  path: /api/user_update
  controller: App\Controller\UserController::update
  methods: PATCH

organization_update:
  path: /api/organization_update/{id}
  controller: App\Controller\OrganizationController::update
  methods: PATCH

preferencies_update:
  path: /api/preferencies_update
  controller: App\Controller\PreferenciesController::update
  methods: PATCH
